//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBosnia_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KorisnickiNalog
    {
        public int KorisnickiNalogID { get; set; }
        public int ZaposlenikID { get; set; }
        public string KorisnickoIme { get; set; }
        public string Lozinka { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
