//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBosnia_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Let
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Let()
        {
            this.PosadaLeta = new HashSet<PosadaLeta>();
            this.PosebnaPonuda = new HashSet<PosebnaPonuda>();
            this.PosebnaPonuda1 = new HashSet<PosebnaPonuda>();
            this.Sjediste = new HashSet<Sjediste>();
            this.Rezervacija = new HashSet<Rezervacija>();
        }
    
        public int LetID { get; set; }
        public int PolazisteID { get; set; }
        public int OdredisteID { get; set; }
        public int ZaposlenikID { get; set; }
        public string BrojLeta { get; set; }
        public int AvionID { get; set; }
        public System.DateTime DatumVrijemePolaska { get; set; }
        public System.DateTime DatumVrijemeDolaska { get; set; }
        public bool StatusLeta { get; set; }
        public Nullable<double> CijenaBussOdrasli { get; set; }
        public Nullable<double> CijenaBussDjeca { get; set; }
        public double CijenaEcoDjeca { get; set; }
        public double CijenaEcoOdrasli { get; set; }
        public Nullable<bool> isPosebnaPonuda { get; set; }
    
        public virtual Avion Avion { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual Grad Grad1 { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosadaLeta> PosadaLeta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosebnaPonuda> PosebnaPonuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PosebnaPonuda> PosebnaPonuda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sjediste> Sjediste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervacija> Rezervacija { get; set; }
    }
}
