//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBosnia_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosadaLeta
    {
        public int PosadaLetaID { get; set; }
        public int LetID { get; set; }
        public int ClanPosadeID { get; set; }
    
        public virtual Let Let { get; set; }
        public virtual Zaposlenik Zaposlenik { get; set; }
    }
}
