//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirBosnia_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezervacija
    {
        public int RezervacijaID { get; set; }
        public int KorisnikID { get; set; }
        public int LetPolazakID { get; set; }
        public int SjedistePolazakID { get; set; }
        public string ImePutnika { get; set; }
        public string PrezimePutnika { get; set; }
        public System.DateTime DatumRodjenjaPutnika { get; set; }
        public string Spol { get; set; }
        public string TipPutnika { get; set; }
        public string TipDokumenta { get; set; }
        public string BrojDokumenta { get; set; }
        public System.DateTime DatumRezervacije { get; set; }
        public double CijenaKarte { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Let Let { get; set; }
        public virtual Sjediste Sjediste { get; set; }
    }
}
